---
# tasks file for codepi
# Move to common
#- name: Install podman
# Create image
- name: Make sure image dir exits
  file:
    path: '{{ docker_dir }}/codepi'
    state: directory
- name: Render Dockerfile
  template:
    src: Dockerfile.j2
    dest: '{{ docker_dir }}/codepi/Dockerfile'
- name: Build image
  shell:
    cmd: 'podman build . -t {{ registry_url }}/{{ codepi_image }}:{{ codepi_tag }}'
    chdir: '{{ docker_dir }}/codepi'
- name: Push to registry
  shell:
    cmd: 'podman push {{ registry_url }}/{{ codepi_image }}:{{ codepi_tag }} --tls-verify=False'
# K8S Deployment
- name: Create namespace
  shell:
    cmd: 'kubectl create namespace {{ codepi_namespace }}'
  become: true
  ignore_errors: true
- name: Ensure manifests folder exits
  file:
    path: '{{ manifest_folder }}'
    state: directory
- name: Render manifests
  template:
    src: '{{ item.src }}'
    dest: '{{ manifest_folder }}/{{ item.dest }}'
  with_items: '{{ manifests }}'
- name: Apply manifests
  shell:
    cmd: 'kubectl apply -f {{ manifest_folder }}/{{ item.dest }} -n {{ codepi_namespace }}'
  with_items: '{{ manifests }}'