apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codepi-ingress
  namespace: {{ codepi_namespace }}
spec:
  rules:
    - host: codepi
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name:  codepi-service
                port:
                  number: 8000
 