---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codepi
  labels:
    app: codepi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codepi
  template:
    metadata:
      labels:
        app: codepi
    spec:
      containers:
      - name: codepi
        #image: linuxserver/code-server:latest
        image: '{{ registry_url }}/{{ codepi_image }}:{{ codepi_tag }}' 
        env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: TZ
          value: 'Etc/UTC'
        - name: PASSWORD
          value: 'password'
        - name: SUDO_PASSWORD
          value: 'password'
        - name: DEFAULT_WORKSPACE
          value: '/code'
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: codepi-claim
          mountPath: /code
        - mountPath: /root/.config/code-server/config.yaml
          name: code-config
          subPath: config.yaml
          readOnly: true
      securityContext:
        fsGroup: 1000
      volumes:
      - name: codepi-claim
        persistentVolumeClaim:
          claimName: codepi-claim
      - name: code-config
        configMap:
          name: code-config
 