---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codepi
  labels:
    app: codepi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codepi
  template:
    metadata:
      labels:
        app: codepi
    spec:
      containers:
      - name: codepi
        image: linuxserver/code-server:latest
        env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: TZ
          value: 'Etc/UTC'
        - name: PASSWORD
          value: 'password'
        - name: SUDO_PASSWORD
          value: 'password'
        - name: DEFAULT_WORKSPACE
          value: '/code'
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: codepi-claim
          mountPath: /code
      securityContext:
        fsGroup: 1000
      volumes:
      - name: codepi-claim
        persistentVolumeClaim:
          claimName: codepi-claim
 