FROM ubuntu:22.04

RUN apt update &&\
    apt install python3 -y &&\
    apt install python3-pip -y &&\
    apt install curl -y

RUN pip install paho-mqtt &&\
    pip install influxdb

WORKDIR /app
RUN curl -fsSL https://code-server.dev/install.sh | sh

CMD ["code-server", "--log", "debug", "--auth", "none", "--proxy-domain", "codepi/dev"]

